In [32]:
import time
import random
from math import *
import operator
import pandas as pd
import numpy as np
import datetime 
import calendar
import matplotlib.pyplot as plt

In [33]:
# Importing File

location = r"file:///C:\Users\nikhil\Downloads\police_department_data%20(1).csv"

In [34]:
df_police=pd.read_csv(location)

In [35]:
# Checking Imported File

df_police.head()

,incident_id,category,crime_description,crime_date,department_district,resolution,address,department_id,location
0,120058272,WEAPON LAWS,POSS OF PROHIBITED WEAPON,2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,12005827212120,"(37.775420706711, -122.403404791479)"
1,120058272,WEAPON LAWS,"FIREARM, LOADED, IN VEHICLE, POSSESSION OR USE",2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED",800 Block of BRYANT ST,12005827212168,"(37.775420706711, -122.403404791479)"
2,141059263,WARRANTS,WARRANT ARREST,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED",KEITH ST / SHAFTER AV,14105926363010,"(37.7299809672996, -122.388856204292)"
3,160013662,NON-CRIMINAL,LOST PROPERTY,2016-01-05 23:50:00,TENDERLOIN,NONE,JONES ST / OFARRELL ST,16001366271000,"(37.7857883766888, -122.412970537591)"
4,160002740,NON-CRIMINAL,LOST PROPERTY,2016-01-01 00:30:00,MISSION,NONE,16TH ST / MISSION ST,16000274071000,"(37.7650501214668, -122.419671780296)"

In [36]:
# Droping column Not Necessary for study

df2=df_police.drop(['incident_id','crime_description','address','department_id','location'

],axis=1)

In [37]:
df2

,category,crime_date,department_district,resolution
0,WEAPON LAWS,2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED"
1,WEAPON LAWS,2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED"
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED"
3,NON-CRIMINAL,2016-01-05 23:50:00,TENDERLOIN,NONE
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,NONE
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,NONE
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,"ARREST, BOOKED"
7,NON-CRIMINAL,2016-01-02 01:02:00,TENDERLOIN,NONE
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,"ARREST, BOOKED"
9,MISSING PERSON,2016-01-01 10:06:00,BAYVIEW,NONE
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,NONE
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,NONE
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,"ARREST, BOOKED"
13,ASSAULT,2016-09-15 07:40:00,INGLESIDE,"ARREST, BOOKED"
14,BURGLARY,2016-01-02 01:43:00,CENTRAL,NONE
15,STOLEN PROPERTY,2016-01-02 11:54:00,SOUTHERN,"ARREST, BOOKED"
16,ROBBERY,2016-01-02 14:11:00,MISSION,NONE
17,ASSAULT,2016-01-02 16:40:00,MISSION,NONE
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,NONE
19,LARCENY/THEFT,2016-01-02 17:39:00,SOUTHERN,JUVENILE BOOKED
20,FRAUD,2016-01-02 21:00:00,NORTHERN,NONE
21,WARRANTS,2016-01-03 04:03:00,NORTHERN,"ARREST, BOOKED"
22,DRUG/NARCOTIC,2016-01-03 06:50:00,MISSION,"ARREST, BOOKED"
23,OTHER OFFENSES,2016-01-03 06:50:00,MISSION,"ARREST, BOOKED"
24,ASSAULT,2016-01-03 09:38:00,RICHMOND,"ARREST, BOOKED"
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,"ARREST, BOOKED"
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,NONE
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,"ARREST, BOOKED"
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,"ARREST, BOOKED"
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,NONE
...,...,...,...,...
150470,FRAUD,2016-05-14 21:22:00,NORTHERN,NONE
150471,NON-CRIMINAL,2016-05-15 07:30:00,RICHMOND,NONE
150472,NON-CRIMINAL,2016-05-07 01:50:00,SOUTHERN,NONE
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,NONE
150474,NON-CRIMINAL,2016-06-13 09:40:00,SOUTHERN,NONE
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,NONE
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,NONE
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,NONE
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,NONE
150479,LARCENY/THEFT,2016-07-22 09:30:00,PARK,NONE
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,NONE
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,NONE
150482,NON-CRIMINAL,2016-09-26 09:10:00,TARAVAL,NONE
150483,NON-CRIMINAL,2016-10-08 23:00:00,TENDERLOIN,NONE
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,NONE
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,NONE
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,NONE
150487,LARCENY/THEFT,2016-12-11 05:30:00,TARAVAL,NONE
150488,NON-CRIMINAL,2016-12-05 08:00:00,MISSION,NONE
150489,FRAUD,2016-07-03 00:01:00,SOUTHERN,NONE
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,NONE
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,NONE
150492,ASSAULT,2016-10-09 21:15:00,MISSION,NONE
150493,ASSAULT,2016-10-21 13:30:00,MISSION,NONE
150494,SECONDARY CODES,2016-09-01 00:01:00,BAYVIEW,NONE
150495,ASSAULT,2016-12-30 21:01:00,PARK,NONE
150496,NON-CRIMINAL,2016-12-30 08:00:00,CENTRAL,NONE
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,NONE
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,NONE
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,NONE

In [38]:
df3=df2

In [39]:
# Getting Month from crime date

df3['month'] = pd.DatetimeIndex(df3['crime_date']).month

In [40]:
month1={1:"Jan" ,2:"Feb" ,3:"Mar" ,4:"April" ,5:"May" ,6:"June" ,7:"July" ,8:"Aug" ,9:"Sep"
       ,10:"Oct" ,11:"Nov" ,12:"Dec"}

In [41]:
df3['month']=[month1[items] for items in df3['month']]

In [42]:
df3['month']

0           Jan
1           Jan
2         April
3           Jan
4           Jan
5           Jan
6           Jan
7           Jan
8           Jan
9           Jan
10          Jan
11          Jan
12          Jan
13          Sep
14          Jan
15          Jan
16          Jan
17          Jan
18          Jan
19          Jan
20          Jan
21          Jan
22          Jan
23          Jan
24          Jan
25          Jan
26          Jan
27          Jan
28          Jan
29          Jan
          ...
150470      May
150471      May
150472      May
150473      May
150474     June
150475     July
150476     July
150477      May
150478     July
150479     July
150480      Aug
150481      Sep
150482      Sep
150483      Oct
150484      Nov
150485      Nov
150486      Nov
150487      Dec
150488      Dec
150489     July
150490      Aug
150491      Oct
150492      Oct
150493      Oct
150494      Sep
150495      Dec
150496      Dec
150497      Dec
150498      Dec
150499      Dec
Name: month, Length: 150500, dtype: object

In [11]:
df3['Day'] = pd.DatetimeIndex(df3['crime_date']).day

In [43]:
df3['crime_date'] = pd.to_datetime(df3['crime_date'])

In [44]:
# Getting day of week(sun, mon, tue)

df3['day_of_week'] = df3['crime_date'].dt.day_name()

In [45]:
df3.day_of_week.unique()

array(['Friday', 'Monday', 'Tuesday', 'Saturday', 'Thursday', 'Sunday',
       'Wednesday'], dtype=object)

In [46]:
(df3['day_of_week'].value_counts()/df3['day_of_week'].count())*100

Friday       15.528904
Saturday     14.732226
Thursday     14.215947
Wednesday    14.174086
Tuesday      14.114286
Monday       13.809302
Sunday       13.425249
Name: day_of_week, dtype: float64

In [47]:
# Getting hour of day (1, 2, 3)

df3['hour'] = df3['crime_date'].dt.hour

In [48]:
df3.hour.unique()

array([11, 14, 23,  0, 21,  1, 12, 10, 22, 13,  7, 16, 17,  4,  6,  9, 15,
       19, 20,  5,  2,  8, 18,  3], dtype=int64)

In [49]:
(df3['hour'].value_counts()/df3['hour'].count())*100

18    6.457143
17    6.351495
12    5.994020
19    5.967442
16    5.751495
15    5.534219
20    5.380731
14    5.063787
21    4.970100
13    4.829236
22    4.716944
0     4.611960
11    4.508970
23    4.367442
10    4.307641
9     3.897010
8     3.704319
1     2.896346
7     2.587375
2     2.321595
3     1.696346
6     1.673090
4     1.252492
5     1.158804
Name: hour, dtype: float64

In [50]:
(df3['hour'].value_counts()/df3['hour'].count())*100

18    6.457143
17    6.351495
12    5.994020
19    5.967442
16    5.751495
15    5.534219
20    5.380731
14    5.063787
21    4.970100
13    4.829236
22    4.716944
0     4.611960
11    4.508970
23    4.367442
10    4.307641
9     3.897010
8     3.704319
1     2.896346
7     2.587375
2     2.321595
3     1.696346
6     1.673090
4     1.252492
5     1.158804
Name: hour, dtype: float64

In [51]:
df33=df3.drop(df3[df3.hour.isin(["9","8","1","2","7","3","6","4","5"
])].index)

In [52]:
df33

,category,crime_date,department_district,resolution,month,day_of_week,hour
0,WEAPON LAWS,2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED",Jan,Friday,11
1,WEAPON LAWS,2016-01-29 11:00:00,SOUTHERN,"ARREST, BOOKED",Jan,Friday,11
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED",April,Monday,14
3,NON-CRIMINAL,2016-01-05 23:50:00,TENDERLOIN,NONE,Jan,Tuesday,23
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,NONE,Jan,Friday,0
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,NONE,Jan,Friday,21
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,0
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,12
9,MISSING PERSON,2016-01-01 10:06:00,BAYVIEW,NONE,Jan,Friday,10
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,NONE,Jan,Friday,22
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,NONE,Jan,Saturday,13
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,"ARREST, BOOKED",Jan,Monday,23
15,STOLEN PROPERTY,2016-01-02 11:54:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,11
16,ROBBERY,2016-01-02 14:11:00,MISSION,NONE,Jan,Saturday,14
17,ASSAULT,2016-01-02 16:40:00,MISSION,NONE,Jan,Saturday,16
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,NONE,Jan,Saturday,17
19,LARCENY/THEFT,2016-01-02 17:39:00,SOUTHERN,JUVENILE BOOKED,Jan,Saturday,17
20,FRAUD,2016-01-02 21:00:00,NORTHERN,NONE,Jan,Saturday,21
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,"ARREST, BOOKED",Jan,Sunday,15
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,NONE,Jan,Sunday,10
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,"ARREST, BOOKED",Jan,Sunday,15
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,"ARREST, BOOKED",Jan,Sunday,17
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,NONE,Jan,Sunday,17
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,NONE,Jan,Sunday,15
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,NONE,Feb,Tuesday,12
33,ASSAULT,2016-02-16 13:10:00,TENDERLOIN,NONE,Feb,Tuesday,13
34,RECOVERED VEHICLE,2016-02-16 16:35:00,MISSION,"ARREST, BOOKED",Feb,Tuesday,16
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,"ARREST, BOOKED",Feb,Tuesday,16
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,NONE,Jan,Sunday,19
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,NONE,Feb,Friday,16
...,...,...,...,...,...,...,...
150460,MISSING PERSON,2016-12-20 10:00:00,CENTRAL,NONE,Dec,Tuesday,10
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,NONE,Dec,Wednesday,22
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,NONE,Mar,Friday,15
150464,NON-CRIMINAL,2016-03-22 18:30:00,PARK,NONE,Mar,Tuesday,18
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,NONE,June,Thursday,16
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,NONE,April,Tuesday,20
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,NONE,April,Tuesday,23
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,NONE,April,Friday,23
150470,FRAUD,2016-05-14 21:22:00,NORTHERN,NONE,May,Saturday,21
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,NONE,May,Saturday,0
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,NONE,July,Monday,22
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,NONE,July,Tuesday,11
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,NONE,May,Monday,13
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,NONE,July,Sunday,16
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,NONE,Aug,Monday,21
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,NONE,Sep,Monday,10
150483,NON-CRIMINAL,2016-10-08 23:00:00,TENDERLOIN,NONE,Oct,Saturday,23
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,NONE,Nov,Tuesday,17
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,NONE,Nov,Monday,13
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,NONE,Nov,Tuesday,13
150489,FRAUD,2016-07-03 00:01:00,SOUTHERN,NONE,July,Sunday,0
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,NONE,Aug,Tuesday,10
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,NONE,Oct,Sunday,18
150492,ASSAULT,2016-10-09 21:15:00,MISSION,NONE,Oct,Sunday,21
150493,ASSAULT,2016-10-21 13:30:00,MISSION,NONE,Oct,Friday,13
150494,SECONDARY CODES,2016-09-01 00:01:00,BAYVIEW,NONE,Sep,Thursday,0
150495,ASSAULT,2016-12-30 21:01:00,PARK,NONE,Dec,Friday,21
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,NONE,Dec,Thursday,20
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,NONE,Dec,Friday,10
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,NONE,Dec,Friday,14

In [53]:
df33.category.unique()

array(['WEAPON LAWS', 'WARRANTS', 'NON-CRIMINAL', 'ASSAULT',
       'OTHER OFFENSES', 'MISSING PERSON', 'LARCENY/THEFT',
       'STOLEN PROPERTY', 'ROBBERY', 'FRAUD', 'BURGLARY', 'VEHICLE THEFT',
       'RECOVERED VEHICLE', 'VANDALISM', 'ARSON', 'DRUG/NARCOTIC',
       'PROSTITUTION', 'SECONDARY CODES', 'SUSPICIOUS OCC', 'TRESPASS',
       'DRUNKENNESS', 'SEX OFFENSES, NON FORCIBLE',
       'SEX OFFENSES, FORCIBLE', 'RUNAWAY', 'DRIVING UNDER THE INFLUENCE',
       'FORGERY/COUNTERFEITING', 'DISORDERLY CONDUCT', 'BRIBERY',
       'FAMILY OFFENSES', 'GAMBLING', 'KIDNAPPING', 'EMBEZZLEMENT',
       'SUICIDE', 'EXTORTION', 'LIQUOR LAWS', 'LOITERING', 'BAD CHECKS',
       'PORNOGRAPHY/OBSCENE MAT', 'TREA'], dtype=object)

In [54]:
(df33['category'].value_counts()/df33['category'].count())*100

LARCENY/THEFT                  28.929375
OTHER OFFENSES                 12.905837
NON-CRIMINAL                   11.865478
ASSAULT                         8.642392
VANDALISM                       5.558413
VEHICLE THEFT                   4.402553
WARRANTS                        3.862140
SUSPICIOUS OCC                  3.707014
BURGLARY                        3.443973
DRUG/NARCOTIC                   2.766139
MISSING PERSON                  2.754336
ROBBERY                         2.041935
FRAUD                           1.857301
SECONDARY CODES                 1.188740
WEAPON LAWS                     1.106118
TRESPASS                        0.886918
STOLEN PROPERTY                 0.564862
SEX OFFENSES, FORCIBLE          0.558118
PROSTITUTION                    0.510062
FORGERY/COUNTERFEITING          0.435871
RECOVERED VEHICLE               0.435028
DRUNKENNESS                     0.284960
DRIVING UNDER THE INFLUENCE     0.228474
DISORDERLY CONDUCT              0.195594
KIDNAPPING                      0.157656
ARSON                           0.123089
EMBEZZLEMENT                    0.121403
LIQUOR LAWS                     0.110443
RUNAWAY                         0.087680
EXTORTION                       0.044683
SUICIDE                         0.042154
BRIBERY                         0.042154
FAMILY OFFENSES                 0.041311
SEX OFFENSES, NON FORCIBLE      0.028665
BAD CHECKS                      0.025292
LOITERING                       0.022763
GAMBLING                        0.016862
PORNOGRAPHY/OBSCENE MAT         0.003372
TREA                            0.000843
Name: category, dtype: float64

In [55]:
# Dropping less frequency variable from category

df4=df33.drop(df33[df33.category.isin(["SEX OFFENSES, FORCIBLE","STOLEN PROPERTY","RECOVERED VEHICLE","DISORDERLY CONDUCT",
                                    "PROSTITUTION","FORGERY/COUNTERFEITING","DRUNKENNESS","DRIVING UNDER THE INFLUENCE","ARSON","KIDNAPPING","EMBEZZLEMENT",
          "LIQUOR LAWS","RUNAWAY","SUICIDE","BRIBERY","EXTORTION","FAMILY OFFENSE","LOITERING","SEX OFFENSES, NON FORCIBLE",
          "BAD CHECKS","GAMBLING","PORNOGRAPHY/OBSCENE MAT","TREA","MISSING PERSON","DRUG/NARCOTIC","ROBBERY","FRAUD",
        "SECONDARY CODES","TRESPASS","FAMILY OFFENSES","WEAPON LAWS"
                                   ])].index)

In [56]:
df4.category.unique()

array(['WARRANTS', 'NON-CRIMINAL', 'ASSAULT', 'OTHER OFFENSES',
       'LARCENY/THEFT', 'BURGLARY', 'VEHICLE THEFT', 'VANDALISM',
       'SUSPICIOUS OCC'], dtype=object)

In [57]:
(df4['category'].value_counts()/df4['category'].count())*100

LARCENY/THEFT     34.721983
OTHER OFFENSES    15.490008
NON-CRIMINAL      14.241336
ASSAULT           10.372881
VANDALISM          6.671389
VEHICLE THEFT      5.284088
WARRANTS           4.635467
SUSPICIOUS OCC     4.449279
BURGLARY           4.133569
Name: category, dtype: float64

In [58]:
df4.resolution.unique()

array(['ARREST, BOOKED', 'NONE', 'JUVENILE BOOKED', 'UNFOUNDED',
       'ARREST, CITED', 'CLEARED-CONTACT JUVENILE FOR MORE INFO',
       'EXCEPTIONAL CLEARANCE', 'COMPLAINANT REFUSES TO PROSECUTE',
       'LOCATED', 'NOT PROSECUTED', 'PSYCHOPATHIC CASE', 'JUVENILE CITED'],
      dtype=object)

In [59]:
(df4['resolution'].value_counts()/df4['resolution'].count())*100

NONE                                      75.842145
ARREST, BOOKED                            22.300025
UNFOUNDED                                  0.994688
JUVENILE BOOKED                            0.522135
EXCEPTIONAL CLEARANCE                      0.205414
ARREST, CITED                              0.098153
CLEARED-CONTACT JUVENILE FOR MORE INFO     0.016190
NOT PROSECUTED                             0.007083
PSYCHOPATHIC CASE                          0.007083
JUVENILE CITED                             0.003036
LOCATED                                    0.002024
COMPLAINANT REFUSES TO PROSECUTE           0.002024
Name: resolution, dtype: float64

In [60]:
# Dropping less frequency variable from resolution

df5=df4.drop(df4[df4.resolution.isin(["CLEARED-CONTACT JUVENILE FOR MORE INFO","NOT PROSECUTED","LOCATED",
                                      "PSYCHOPATHIC CASE","JUVENILE CITED","COMPLAINANT REFUSES TO PROSECUTE",
                                      "JUVENILE DIVERTED","PROSECUTED BY OUTSIDE AGENCY","UNFOUNDED","JUVENILE BOOKED",
                                      "EXCEPTIONAL CLEARANCE","ARREST, CITED","CLEARED-CONTACT JUVENILE FOR MORE INFO",
                                    "NOT PROSECUTED","LOCATED","PSYCHOPATHIC CASE","JUVENILE CITED",
                                      "COMPLAINANT REFUSES TO PROSECUTE","JUVENILE DIVERTED","PROSECUTED BY OUTSIDE AGENCY"
])].index)

In [61]:
df5.resolution.unique()

array(['ARREST, BOOKED', 'NONE'], dtype=object)

In [62]:
(df5['resolution'].value_counts()/df5['resolution'].count())*100

NONE              77.277836
ARREST, BOOKED    22.722164
Name: resolution, dtype: float64

In [64]:
df5.department_district.unique()

array(['BAYVIEW', 'TENDERLOIN', 'MISSION', 'NORTHERN', 'SOUTHERN',
       'TARAVAL', 'INGLESIDE', 'CENTRAL', 'PARK', 'RICHMOND', nan],
      dtype=object)

In [66]:
(df5['department_district'].value_counts()/df5['department_district'].count())*100

SOUTHERN      19.158040
NORTHERN      13.681074
CENTRAL       12.707758
MISSION       12.023137
BAYVIEW        9.201138
TARAVAL        7.521549
INGLESIDE      7.485462
RICHMOND       6.539984
TENDERLOIN     5.955376
PARK           5.726482
Name: department_district, dtype: float64

In [67]:
df6=df5.drop(df5[df5.department_district.isin(["TENDERLOIN",'RICHMOND', 'PARK'
])].index)

In [68]:
df6.department_district.unique()

array(['BAYVIEW', 'MISSION', 'NORTHERN', 'SOUTHERN', 'TARAVAL',
       'INGLESIDE', 'CENTRAL', nan], dtype=object)

In [69]:
(df6['department_district'].value_counts()/df6['department_district'].count())*100

SOUTHERN     23.426842
NORTHERN     16.729496
CENTRAL      15.539305
MISSION      14.702137
BAYVIEW      11.251340
TARAVAL       9.197504
INGLESIDE     9.153376
Name: department_district, dtype: float64

In [70]:
df6

,category,crime_date,department_district,resolution,month,day_of_week,hour
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED",April,Monday,14
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,NONE,Jan,Friday,0
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,NONE,Jan,Friday,21
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,0
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,12
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,NONE,Jan,Friday,22
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,NONE,Jan,Saturday,13
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,"ARREST, BOOKED",Jan,Monday,23
17,ASSAULT,2016-01-02 16:40:00,MISSION,NONE,Jan,Saturday,16
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,NONE,Jan,Saturday,17
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,"ARREST, BOOKED",Jan,Sunday,15
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,NONE,Jan,Sunday,10
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,"ARREST, BOOKED",Jan,Sunday,15
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,"ARREST, BOOKED",Jan,Sunday,17
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,NONE,Jan,Sunday,17
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,NONE,Jan,Sunday,15
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,NONE,Feb,Tuesday,12
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,"ARREST, BOOKED",Feb,Tuesday,16
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,NONE,Jan,Sunday,19
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,NONE,Feb,Friday,16
39,OTHER OFFENSES,2016-01-04 20:15:00,INGLESIDE,NONE,Jan,Monday,20
41,ASSAULT,2016-01-03 21:30:00,SOUTHERN,NONE,Jan,Sunday,21
42,LARCENY/THEFT,2016-01-04 19:40:00,MISSION,NONE,Jan,Monday,19
43,NON-CRIMINAL,2016-01-04 21:45:00,SOUTHERN,NONE,Jan,Monday,21
44,BURGLARY,2016-01-04 20:08:00,MISSION,NONE,Jan,Monday,20
46,BURGLARY,2016-10-26 19:37:00,INGLESIDE,"ARREST, BOOKED",Oct,Wednesday,19
50,ASSAULT,2016-01-04 23:00:00,SOUTHERN,NONE,Jan,Monday,23
58,ASSAULT,2016-01-05 14:06:00,CENTRAL,NONE,Jan,Tuesday,14
59,OTHER OFFENSES,2016-01-05 15:15:00,NORTHERN,"ARREST, BOOKED",Jan,Tuesday,15
60,OTHER OFFENSES,2016-01-05 15:14:00,BAYVIEW,"ARREST, BOOKED",Jan,Tuesday,15
...,...,...,...,...,...,...,...
150448,ASSAULT,2016-04-29 10:00:00,SOUTHERN,NONE,April,Friday,10
150450,ASSAULT,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,18
150451,SUSPICIOUS OCC,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,18
150453,NON-CRIMINAL,2016-12-02 16:47:00,NORTHERN,NONE,Dec,Friday,16
150454,BURGLARY,2016-11-24 00:30:00,INGLESIDE,NONE,Nov,Thursday,0
150456,NON-CRIMINAL,2016-12-09 19:30:00,TARAVAL,NONE,Dec,Friday,19
150457,ASSAULT,2016-12-14 11:05:00,SOUTHERN,NONE,Dec,Wednesday,11
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,NONE,Dec,Wednesday,22
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,NONE,Mar,Friday,15
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,NONE,June,Thursday,16
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,NONE,April,Tuesday,20
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,NONE,April,Tuesday,23
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,NONE,April,Friday,23
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,NONE,May,Saturday,0
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,NONE,July,Monday,22
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,NONE,July,Tuesday,11
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,NONE,May,Monday,13
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,NONE,July,Sunday,16
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,NONE,Aug,Monday,21
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,NONE,Sep,Monday,10
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,NONE,Nov,Tuesday,17
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,NONE,Nov,Monday,13
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,NONE,Nov,Tuesday,13
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,NONE,Aug,Tuesday,10
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,NONE,Oct,Sunday,18
150492,ASSAULT,2016-10-09 21:15:00,MISSION,NONE,Oct,Sunday,21
150493,ASSAULT,2016-10-21 13:30:00,MISSION,NONE,Oct,Friday,13
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,NONE,Dec,Thursday,20
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,NONE,Dec,Friday,10
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,NONE,Dec,Friday,14

In [103]:
df7=df6.dropna()

In [104]:
df7

,category,crime_date,department_district,resolution,month,day_of_week,hour
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED",April,Monday,14
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,NONE,Jan,Friday,0
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,NONE,Jan,Friday,21
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,0
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,12
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,NONE,Jan,Friday,22
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,NONE,Jan,Saturday,13
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,"ARREST, BOOKED",Jan,Monday,23
17,ASSAULT,2016-01-02 16:40:00,MISSION,NONE,Jan,Saturday,16
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,NONE,Jan,Saturday,17
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,"ARREST, BOOKED",Jan,Sunday,15
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,NONE,Jan,Sunday,10
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,"ARREST, BOOKED",Jan,Sunday,15
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,"ARREST, BOOKED",Jan,Sunday,17
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,NONE,Jan,Sunday,17
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,NONE,Jan,Sunday,15
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,NONE,Feb,Tuesday,12
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,"ARREST, BOOKED",Feb,Tuesday,16
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,NONE,Jan,Sunday,19
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,NONE,Feb,Friday,16
39,OTHER OFFENSES,2016-01-04 20:15:00,INGLESIDE,NONE,Jan,Monday,20
41,ASSAULT,2016-01-03 21:30:00,SOUTHERN,NONE,Jan,Sunday,21
42,LARCENY/THEFT,2016-01-04 19:40:00,MISSION,NONE,Jan,Monday,19
43,NON-CRIMINAL,2016-01-04 21:45:00,SOUTHERN,NONE,Jan,Monday,21
44,BURGLARY,2016-01-04 20:08:00,MISSION,NONE,Jan,Monday,20
46,BURGLARY,2016-10-26 19:37:00,INGLESIDE,"ARREST, BOOKED",Oct,Wednesday,19
50,ASSAULT,2016-01-04 23:00:00,SOUTHERN,NONE,Jan,Monday,23
58,ASSAULT,2016-01-05 14:06:00,CENTRAL,NONE,Jan,Tuesday,14
59,OTHER OFFENSES,2016-01-05 15:15:00,NORTHERN,"ARREST, BOOKED",Jan,Tuesday,15
60,OTHER OFFENSES,2016-01-05 15:14:00,BAYVIEW,"ARREST, BOOKED",Jan,Tuesday,15
...,...,...,...,...,...,...,...
150448,ASSAULT,2016-04-29 10:00:00,SOUTHERN,NONE,April,Friday,10
150450,ASSAULT,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,18
150451,SUSPICIOUS OCC,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,18
150453,NON-CRIMINAL,2016-12-02 16:47:00,NORTHERN,NONE,Dec,Friday,16
150454,BURGLARY,2016-11-24 00:30:00,INGLESIDE,NONE,Nov,Thursday,0
150456,NON-CRIMINAL,2016-12-09 19:30:00,TARAVAL,NONE,Dec,Friday,19
150457,ASSAULT,2016-12-14 11:05:00,SOUTHERN,NONE,Dec,Wednesday,11
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,NONE,Dec,Wednesday,22
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,NONE,Mar,Friday,15
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,NONE,June,Thursday,16
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,NONE,April,Tuesday,20
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,NONE,April,Tuesday,23
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,NONE,April,Friday,23
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,NONE,May,Saturday,0
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,NONE,July,Monday,22
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,NONE,July,Tuesday,11
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,NONE,May,Monday,13
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,NONE,July,Sunday,16
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,NONE,Aug,Monday,21
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,NONE,Sep,Monday,10
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,NONE,Nov,Tuesday,17
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,NONE,Nov,Monday,13
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,NONE,Nov,Tuesday,13
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,NONE,Aug,Tuesday,10
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,NONE,Oct,Sunday,18
150492,ASSAULT,2016-10-09 21:15:00,MISSION,NONE,Oct,Sunday,21
150493,ASSAULT,2016-10-21 13:30:00,MISSION,NONE,Oct,Friday,13
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,NONE,Dec,Thursday,20
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,NONE,Dec,Friday,10
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,NONE,Dec,Friday,14

# Variable conversion to binary

In [105]:
# For day_of_week
from sklearn.preprocessing import LabelBinarizer

lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(df7["day_of_week"])
dfw=pd.DataFrame(lb_results, columns=lb_style.classes_)
dfw

       Friday  Monday  Saturday  Sunday  Thursday  Tuesday  Wednesday
0           0       1         0       0         0        0          0
1           1       0         0       0         0        0          0
2           1       0         0       0         0        0          0
3           0       0         1       0         0        0          0
4           0       0         1       0         0        0          0
5           1       0         0       0         0        0          0
6           0       0         1       0         0        0          0
7           0       1         0       0         0        0          0
8           0       0         1       0         0        0          0
9           0       0         1       0         0        0          0
10          0       0         0       1         0        0          0
11          0       0         0       1         0        0          0
12          0       0         0       1         0        0          0
13          0       0         0       1         0        0          0
14          0       0         0       1         0        0          0
15          0       0         0       1         0        0          0
16          0       0         0       0         0        1          0
17          0       0         0       0         0        1          0
18          0       0         0       1         0        0          0
19          1       0         0       0         0        0          0
20          0       1         0       0         0        0          0
21          0       0         0       1         0        0          0
22          0       1         0       0         0        0          0
23          0       1         0       0         0        0          0
24          0       1         0       0         0        0          0
25          0       0         0       0         0        0          1
26          0       1         0       0         0        0          0
27          0       0         0       0         0        1          0
28          0       0         0       0         0        1          0
29          0       0         0       0         0        1          0
...       ...     ...       ...     ...       ...      ...        ...
79285       1       0         0       0         0        0          0
79286       0       1         0       0         0        0          0
79287       0       1         0       0         0        0          0
79288       1       0         0       0         0        0          0
79289       0       0         0       0         1        0          0
79290       1       0         0       0         0        0          0
79291       0       0         0       0         0        0          1
79292       0       0         0       0         0        0          1
79293       1       0         0       0         0        0          0
79294       0       0         0       0         1        0          0
79295       0       0         0       0         0        1          0
79296       0       0         0       0         0        1          0
79297       1       0         0       0         0        0          0
79298       0       0         1       0         0        0          0
79299       0       1         0       0         0        0          0
79300       0       0         0       0         0        1          0
79301       0       1         0       0         0        0          0
79302       0       0         0       1         0        0          0
79303       0       1         0       0         0        0          0
79304       0       1         0       0         0        0          0
79305       0       0         0       0         0        1          0
79306       0       1         0       0         0        0          0
79307       0       0         0       0         0        1          0
79308       0       0         0       0         0        1          0
79309       0       0         0       1         0        0          0
79310       0       0         0       1         0        0          0
79311       1       0         0       0         0        0          0
79312       0       0         0       0         1        0          0
79313       1       0         0       0         0        0          0
79314       1       0         0       0         0        0          0

[79315 rows x 7 columns]

In [106]:
# For category

lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(df7["category"])
ctg=pd.DataFrame(lb_results, columns=lb_style.classes_)
ctg

,ASSAULT,BURGLARY,LARCENY/THEFT,NON-CRIMINAL,OTHER OFFENSES,SUSPICIOUS OCC,VANDALISM,VEHICLE THEFT,WARRANTS
0,0,0,0,0,0,0,0,0,1
1,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,1
5,0,0,1,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0
7,0,0,0,0,1,0,0,0,0
8,1,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,0,0
10,0,0,0,0,1,0,0,0,0
11,0,0,0,0,1,0,0,0,0
12,0,1,0,0,0,0,0,0,0
13,0,0,0,0,1,0,0,0,0
14,0,0,0,1,0,0,0,0,0
15,0,0,0,0,0,0,0,1,0
16,0,0,1,0,0,0,0,0,0
17,0,0,0,0,1,0,0,0,0
18,0,0,0,1,0,0,0,0,0
19,0,0,0,1,0,0,0,0,0
20,0,0,0,0,1,0,0,0,0
21,1,0,0,0,0,0,0,0,0
22,0,0,1,0,0,0,0,0,0
23,0,0,0,1,0,0,0,0,0
24,0,1,0,0,0,0,0,0,0
25,0,1,0,0,0,0,0,0,0
26,1,0,0,0,0,0,0,0,0
27,1,0,0,0,0,0,0,0,0
28,0,0,0,0,1,0,0,0,0
29,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
79285,1,0,0,0,0,0,0,0,0
79286,1,0,0,0,0,0,0,0,0
79287,0,0,0,0,0,1,0,0,0
79288,0,0,0,1,0,0,0,0,0
79289,0,1,0,0,0,0,0,0,0
79290,0,0,0,1,0,0,0,0,0
79291,1,0,0,0,0,0,0,0,0
79292,0,0,1,0,0,0,0,0,0
79293,0,0,0,1,0,0,0,0,0
79294,1,0,0,0,0,0,0,0,0
79295,0,0,1,0,0,0,0,0,0
79296,0,0,0,1,0,0,0,0,0
79297,0,0,1,0,0,0,0,0,0
79298,0,0,0,1,0,0,0,0,0
79299,0,0,0,1,0,0,0,0,0
79300,0,0,0,1,0,0,0,0,0
79301,0,0,1,0,0,0,0,0,0
79302,0,0,0,1,0,0,0,0,0
79303,0,0,0,1,0,0,0,0,0
79304,0,0,0,1,0,0,0,0,0
79305,0,0,0,1,0,0,0,0,0
79306,0,0,0,1,0,0,0,0,0
79307,0,0,1,0,0,0,0,0,0
79308,1,0,0,0,0,0,0,0,0
79309,1,0,0,0,0,0,0,0,0
79310,1,0,0,0,0,0,0,0,0
79311,1,0,0,0,0,0,0,0,0
79312,0,0,1,0,0,0,0,0,0
79313,0,0,1,0,0,0,0,0,0
79314,0,0,0,0,1,0,0,0,0

In [107]:
# For month
from sklearn.preprocessing import LabelBinarizer

lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(df7["month"])
mth=pd.DataFrame(lb_results, columns=lb_style.classes_)
mth

       April  Aug  Dec  Feb  Jan  July  June  Mar  May  Nov  Oct  Sep
0          1    0    0    0    0     0     0    0    0    0    0    0
1          0    0    0    0    1     0     0    0    0    0    0    0
2          0    0    0    0    1     0     0    0    0    0    0    0
3          0    0    0    0    1     0     0    0    0    0    0    0
4          0    0    0    0    1     0     0    0    0    0    0    0
5          0    0    0    0    1     0     0    0    0    0    0    0
6          0    0    0    0    1     0     0    0    0    0    0    0
7          0    0    0    0    1     0     0    0    0    0    0    0
8          0    0    0    0    1     0     0    0    0    0    0    0
9          0    0    0    0    1     0     0    0    0    0    0    0
10         0    0    0    0    1     0     0    0    0    0    0    0
11         0    0    0    0    1     0     0    0    0    0    0    0
12         0    0    0    0    1     0     0    0    0    0    0    0
13         0    0    0    0    1     0     0    0    0    0    0    0
14         0    0    0    0    1     0     0    0    0    0    0    0
15         0    0    0    0    1     0     0    0    0    0    0    0
16         0    0    0    1    0     0     0    0    0    0    0    0
17         0    0    0    1    0     0     0    0    0    0    0    0
18         0    0    0    0    1     0     0    0    0    0    0    0
19         0    0    0    1    0     0     0    0    0    0    0    0
20         0    0    0    0    1     0     0    0    0    0    0    0
21         0    0    0    0    1     0     0    0    0    0    0    0
22         0    0    0    0    1     0     0    0    0    0    0    0
23         0    0    0    0    1     0     0    0    0    0    0    0
24         0    0    0    0    1     0     0    0    0    0    0    0
25         0    0    0    0    0     0     0    0    0    0    1    0
26         0    0    0    0    1     0     0    0    0    0    0    0
27         0    0    0    0    1     0     0    0    0    0    0    0
28         0    0    0    0    1     0     0    0    0    0    0    0
29         0    0    0    0    1     0     0    0    0    0    0    0
...      ...  ...  ...  ...  ...   ...   ...  ...  ...  ...  ...  ...
79285      1    0    0    0    0     0     0    0    0    0    0    0
79286      0    0    0    0    0     0     0    0    0    1    0    0
79287      0    0    0    0    0     0     0    0    0    1    0    0
79288      0    0    1    0    0     0     0    0    0    0    0    0
79289      0    0    0    0    0     0     0    0    0    1    0    0
79290      0    0    1    0    0     0     0    0    0    0    0    0
79291      0    0    1    0    0     0     0    0    0    0    0    0
79292      0    0    1    0    0     0     0    0    0    0    0    0
79293      0    0    0    0    0     0     0    1    0    0    0    0
79294      0    0    0    0    0     0     1    0    0    0    0    0
79295      1    0    0    0    0     0     0    0    0    0    0    0
79296      1    0    0    0    0     0     0    0    0    0    0    0
79297      1    0    0    0    0     0     0    0    0    0    0    0
79298      0    0    0    0    0     0     0    0    1    0    0    0
79299      0    0    0    0    0     1     0    0    0    0    0    0
79300      0    0    0    0    0     1     0    0    0    0    0    0
79301      0    0    0    0    0     0     0    0    1    0    0    0
79302      0    0    0    0    0     1     0    0    0    0    0    0
79303      0    1    0    0    0     0     0    0    0    0    0    0
79304      0    0    0    0    0     0     0    0    0    0    0    1
79305      0    0    0    0    0     0     0    0    0    1    0    0
79306      0    0    0    0    0     0     0    0    0    1    0    0
79307      0    0    0    0    0     0     0    0    0    1    0    0
79308      0    1    0    0    0     0     0    0    0    0    0    0
79309      0    0    0    0    0     0     0    0    0    0    1    0
79310      0    0    0    0    0     0     0    0    0    0    1    0
79311      0    0    0    0    0     0     0    0    0    0    1    0
79312      0    0    1    0    0     0     0    0    0    0    0    0
79313      0    0    1    0    0     0     0    0    0    0    0    0
79314      0    0    1    0    0     0     0    0    0    0    0    0

[79315 rows x 12 columns]

In [108]:
# For department_district
from sklearn.preprocessing import LabelBinarizer

lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(df7["department_district"])
dd=pd.DataFrame(lb_results, columns=lb_style.classes_)
dd

       BAYVIEW  CENTRAL  INGLESIDE  MISSION  NORTHERN  SOUTHERN  TARAVAL
0            1        0          0        0         0         0        0
1            0        0          0        1         0         0        0
2            0        0          0        0         1         0        0
3            0        0          0        0         0         1        0
4            0        0          0        0         0         1        0
5            0        0          0        0         0         0        1
6            0        0          0        0         0         0        1
7            1        0          0        0         0         0        0
8            0        0          0        1         0         0        0
9            0        0          1        0         0         0        0
10           0        0          0        0         0         0        1
11           0        0          0        1         0         0        0
12           0        0          0        0         1         0        0
13           0        0          0        1         0         0        0
14           0        0          1        0         0         0        0
15           0        1          0        0         0         0        0
16           0        0          1        0         0         0        0
17           0        0          0        1         0         0        0
18           0        0          1        0         0         0        0
19           0        0          0        0         0         1        0
20           0        0          1        0         0         0        0
21           0        0          0        0         0         1        0
22           0        0          0        1         0         0        0
23           0        0          0        0         0         1        0
24           0        0          0        1         0         0        0
25           0        0          1        0         0         0        0
26           0        0          0        0         0         1        0
27           0        1          0        0         0         0        0
28           0        0          0        0         1         0        0
29           1        0          0        0         0         0        0
...        ...      ...        ...      ...       ...       ...      ...
79285        0        0          0        0         0         1        0
79286        0        0          0        0         1         0        0
79287        0        0          0        0         1         0        0
79288        0        0          0        0         1         0        0
79289        0        0          1        0         0         0        0
79290        0        0          0        0         0         0        1
79291        0        0          0        0         0         1        0
79292        0        1          0        0         0         0        0
79293        0        0          0        0         1         0        0
79294        1        0          0        0         0         0        0
79295        0        1          0        0         0         0        0
79296        0        1          0        0         0         0        0
79297        0        0          0        1         0         0        0
79298        0        1          0        0         0         0        0
79299        0        1          0        0         0         0        0
79300        0        0          0        0         0         1        0
79301        0        1          0        0         0         0        0
79302        0        0          0        0         0         1        0
79303        0        1          0        0         0         0        0
79304        0        0          0        0         0         0        1
79305        0        0          0        0         0         1        0
79306        0        0          0        0         0         1        0
79307        0        1          0        0         0         0        0
79308        1        0          0        0         0         0        0
79309        0        0          0        0         0         1        0
79310        0        0          0        1         0         0        0
79311        0        0          0        1         0         0        0
79312        0        1          0        0         0         0        0
79313        0        1          0        0         0         0        0
79314        0        0          0        0         0         1        0

[79315 rows x 7 columns]

In [109]:
hr_gp={0:'0-3' ,1:'0-3' ,2:'0-3' ,3:'0-3' ,4:'4-7' ,5:'4-7' ,6:'4-7' ,7:'4-7' ,8:'8-11' ,9:'8-11' ,
10:'8-11' ,11:'8-11' ,12:'12-15' ,13:'12-15',14:'12-15',15:'12-15',16:'16-19',17:'16-19',18:'16-19',
      19:'16-19',20:'20-23',21:'20-23',22:'20-23',23:'20-23'}

In [110]:
df7.hour=[hr_gp[items] for items in df7.hour]

C:\Users\nikhil\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [111]:
df7.hour.unique()

array(['12-15', '0-3', '20-23', '16-19', '8-11'], dtype=object)

In [112]:
lb_style = LabelBinarizer()
lb_results = lb_style.fit_transform(df7["hour"])
hrr=pd.DataFrame(lb_results, columns=lb_style.classes_)
hrr

       0-3  12-15  16-19  20-23  8-11
0        0      1      0      0     0
1        1      0      0      0     0
2        0      0      0      1     0
3        1      0      0      0     0
4        0      1      0      0     0
5        0      0      0      1     0
6        0      1      0      0     0
7        0      0      0      1     0
8        0      0      1      0     0
9        0      0      1      0     0
10       0      1      0      0     0
11       0      0      0      0     1
12       0      1      0      0     0
13       0      0      1      0     0
14       0      0      1      0     0
15       0      1      0      0     0
16       0      1      0      0     0
17       0      0      1      0     0
18       0      0      1      0     0
19       0      0      1      0     0
20       0      0      0      1     0
21       0      0      0      1     0
22       0      0      1      0     0
23       0      0      0      1     0
24       0      0      0      1     0
25       0      0      1      0     0
26       0      0      0      1     0
27       0      1      0      0     0
28       0      1      0      0     0
29       0      1      0      0     0
...    ...    ...    ...    ...   ...
79285    0      0      0      0     1
79286    0      0      1      0     0
79287    0      0      1      0     0
79288    0      0      1      0     0
79289    1      0      0      0     0
79290    0      0      1      0     0
79291    0      0      0      0     1
79292    0      0      0      1     0
79293    0      1      0      0     0
79294    0      0      1      0     0
79295    0      0      0      1     0
79296    0      0      0      1     0
79297    0      0      0      1     0
79298    1      0      0      0     0
79299    0      0      0      1     0
79300    0      0      0      0     1
79301    0      1      0      0     0
79302    0      0      1      0     0
79303    0      0      0      1     0
79304    0      0      0      0     1
79305    0      0      1      0     0
79306    0      1      0      0     0
79307    0      1      0      0     0
79308    0      0      0      0     1
79309    0      0      1      0     0
79310    0      0      0      1     0
79311    0      1      0      0     0
79312    0      0      0      1     0
79313    0      0      0      0     1
79314    0      1      0      0     0

[79315 rows x 5 columns]

In [113]:
df8=df7

In [115]:
df8

,category,crime_date,department_district,resolution,month,day_of_week,hour
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,"ARREST, BOOKED",April,Monday,12-15
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,NONE,Jan,Friday,0-3
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,NONE,Jan,Friday,20-23
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,0-3
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,"ARREST, BOOKED",Jan,Saturday,12-15
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,NONE,Jan,Friday,20-23
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,NONE,Jan,Saturday,12-15
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,"ARREST, BOOKED",Jan,Monday,20-23
17,ASSAULT,2016-01-02 16:40:00,MISSION,NONE,Jan,Saturday,16-19
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,NONE,Jan,Saturday,16-19
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,"ARREST, BOOKED",Jan,Sunday,12-15
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,NONE,Jan,Sunday,8-11
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,"ARREST, BOOKED",Jan,Sunday,12-15
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,"ARREST, BOOKED",Jan,Sunday,16-19
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,NONE,Jan,Sunday,16-19
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,NONE,Jan,Sunday,12-15
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,NONE,Feb,Tuesday,12-15
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,"ARREST, BOOKED",Feb,Tuesday,16-19
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,NONE,Jan,Sunday,16-19
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,NONE,Feb,Friday,16-19
39,OTHER OFFENSES,2016-01-04 20:15:00,INGLESIDE,NONE,Jan,Monday,20-23
41,ASSAULT,2016-01-03 21:30:00,SOUTHERN,NONE,Jan,Sunday,20-23
42,LARCENY/THEFT,2016-01-04 19:40:00,MISSION,NONE,Jan,Monday,16-19
43,NON-CRIMINAL,2016-01-04 21:45:00,SOUTHERN,NONE,Jan,Monday,20-23
44,BURGLARY,2016-01-04 20:08:00,MISSION,NONE,Jan,Monday,20-23
46,BURGLARY,2016-10-26 19:37:00,INGLESIDE,"ARREST, BOOKED",Oct,Wednesday,16-19
50,ASSAULT,2016-01-04 23:00:00,SOUTHERN,NONE,Jan,Monday,20-23
58,ASSAULT,2016-01-05 14:06:00,CENTRAL,NONE,Jan,Tuesday,12-15
59,OTHER OFFENSES,2016-01-05 15:15:00,NORTHERN,"ARREST, BOOKED",Jan,Tuesday,12-15
60,OTHER OFFENSES,2016-01-05 15:14:00,BAYVIEW,"ARREST, BOOKED",Jan,Tuesday,12-15
...,...,...,...,...,...,...,...
150448,ASSAULT,2016-04-29 10:00:00,SOUTHERN,NONE,April,Friday,8-11
150450,ASSAULT,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,16-19
150451,SUSPICIOUS OCC,2016-11-28 18:53:00,NORTHERN,NONE,Nov,Monday,16-19
150453,NON-CRIMINAL,2016-12-02 16:47:00,NORTHERN,NONE,Dec,Friday,16-19
150454,BURGLARY,2016-11-24 00:30:00,INGLESIDE,NONE,Nov,Thursday,0-3
150456,NON-CRIMINAL,2016-12-09 19:30:00,TARAVAL,NONE,Dec,Friday,16-19
150457,ASSAULT,2016-12-14 11:05:00,SOUTHERN,NONE,Dec,Wednesday,8-11
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,NONE,Dec,Wednesday,20-23
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,NONE,Mar,Friday,12-15
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,NONE,June,Thursday,16-19
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,NONE,April,Tuesday,20-23
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,NONE,April,Tuesday,20-23
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,NONE,April,Friday,20-23
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,NONE,May,Saturday,0-3
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,NONE,July,Monday,20-23
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,NONE,July,Tuesday,8-11
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,NONE,May,Monday,12-15
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,NONE,July,Sunday,16-19
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,NONE,Aug,Monday,20-23
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,NONE,Sep,Monday,8-11
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,NONE,Nov,Tuesday,16-19
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,NONE,Nov,Monday,12-15
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,NONE,Nov,Tuesday,12-15
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,NONE,Aug,Tuesday,8-11
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,NONE,Oct,Sunday,16-19
150492,ASSAULT,2016-10-09 21:15:00,MISSION,NONE,Oct,Sunday,20-23
150493,ASSAULT,2016-10-21 13:30:00,MISSION,NONE,Oct,Friday,12-15
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,NONE,Dec,Thursday,20-23
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,NONE,Dec,Friday,8-11
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,NONE,Dec,Friday,12-15

In [116]:
# For resolution
df8['res_arrest']=df7["resolution"]
#df12['res_none']=df12['resolution']

C:\Users\nikhil\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [117]:
df8["resolution"].unique()

array(['ARREST, BOOKED', 'NONE'], dtype=object)

In [118]:
a_b={"NONE":0 ,"ARREST, BOOKED":1}
df8.resolution=[a_b[items] for items in df8.resolution]

C:\Users\nikhil\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [119]:
rstt=df8['resolution']

In [120]:
rstt

2         1
4         0
5         0
6         1
8         1
10        0
11        0
12        1
17        0
18        0
25        1
26        0
27        1
28        1
29        0
30        0
32        0
35        1
36        0
37        0
39        0
41        0
42        0
43        0
44        0
46        1
50        0
58        0
59        1
60        1
         ..
150448    0
150450    0
150451    0
150453    0
150454    0
150456    0
150457    0
150461    0
150463    0
150465    0
150467    0
150468    0
150469    0
150473    0
150475    0
150476    0
150477    0
150478    0
150480    0
150481    0
150484    0
150485    0
150486    0
150490    0
150491    0
150492    0
150493    0
150497    0
150498    0
150499    0
Name: resolution, Length: 79315, dtype: int64

In [121]:
df9=df7

In [123]:
df9

,category,crime_date,department_district,resolution,month,day_of_week,hour,res_arrest
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,1,April,Monday,12-15,"ARREST, BOOKED"
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,0,Jan,Friday,0-3,NONE
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,0,Jan,Friday,20-23,NONE
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,1,Jan,Saturday,0-3,"ARREST, BOOKED"
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,1,Jan,Saturday,12-15,"ARREST, BOOKED"
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,0,Jan,Friday,20-23,NONE
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,0,Jan,Saturday,12-15,NONE
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,1,Jan,Monday,20-23,"ARREST, BOOKED"
17,ASSAULT,2016-01-02 16:40:00,MISSION,0,Jan,Saturday,16-19,NONE
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,0,Jan,Saturday,16-19,NONE
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,1,Jan,Sunday,12-15,"ARREST, BOOKED"
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,0,Jan,Sunday,8-11,NONE
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,1,Jan,Sunday,12-15,"ARREST, BOOKED"
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,1,Jan,Sunday,16-19,"ARREST, BOOKED"
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,0,Jan,Sunday,16-19,NONE
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,0,Jan,Sunday,12-15,NONE
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,0,Feb,Tuesday,12-15,NONE
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,1,Feb,Tuesday,16-19,"ARREST, BOOKED"
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,0,Jan,Sunday,16-19,NONE
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,0,Feb,Friday,16-19,NONE
39,OTHER OFFENSES,2016-01-04 20:15:00,INGLESIDE,0,Jan,Monday,20-23,NONE
41,ASSAULT,2016-01-03 21:30:00,SOUTHERN,0,Jan,Sunday,20-23,NONE
42,LARCENY/THEFT,2016-01-04 19:40:00,MISSION,0,Jan,Monday,16-19,NONE
43,NON-CRIMINAL,2016-01-04 21:45:00,SOUTHERN,0,Jan,Monday,20-23,NONE
44,BURGLARY,2016-01-04 20:08:00,MISSION,0,Jan,Monday,20-23,NONE
46,BURGLARY,2016-10-26 19:37:00,INGLESIDE,1,Oct,Wednesday,16-19,"ARREST, BOOKED"
50,ASSAULT,2016-01-04 23:00:00,SOUTHERN,0,Jan,Monday,20-23,NONE
58,ASSAULT,2016-01-05 14:06:00,CENTRAL,0,Jan,Tuesday,12-15,NONE
59,OTHER OFFENSES,2016-01-05 15:15:00,NORTHERN,1,Jan,Tuesday,12-15,"ARREST, BOOKED"
60,OTHER OFFENSES,2016-01-05 15:14:00,BAYVIEW,1,Jan,Tuesday,12-15,"ARREST, BOOKED"
...,...,...,...,...,...,...,...,...
150448,ASSAULT,2016-04-29 10:00:00,SOUTHERN,0,April,Friday,8-11,NONE
150450,ASSAULT,2016-11-28 18:53:00,NORTHERN,0,Nov,Monday,16-19,NONE
150451,SUSPICIOUS OCC,2016-11-28 18:53:00,NORTHERN,0,Nov,Monday,16-19,NONE
150453,NON-CRIMINAL,2016-12-02 16:47:00,NORTHERN,0,Dec,Friday,16-19,NONE
150454,BURGLARY,2016-11-24 00:30:00,INGLESIDE,0,Nov,Thursday,0-3,NONE
150456,NON-CRIMINAL,2016-12-09 19:30:00,TARAVAL,0,Dec,Friday,16-19,NONE
150457,ASSAULT,2016-12-14 11:05:00,SOUTHERN,0,Dec,Wednesday,8-11,NONE
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,0,Dec,Wednesday,20-23,NONE
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,0,Mar,Friday,12-15,NONE
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,0,June,Thursday,16-19,NONE
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,0,April,Tuesday,20-23,NONE
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,0,April,Tuesday,20-23,NONE
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,0,April,Friday,20-23,NONE
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,0,May,Saturday,0-3,NONE
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,0,July,Monday,20-23,NONE
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,0,July,Tuesday,8-11,NONE
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,0,May,Monday,12-15,NONE
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,0,July,Sunday,16-19,NONE
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,0,Aug,Monday,20-23,NONE
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,0,Sep,Monday,8-11,NONE
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,0,Nov,Tuesday,16-19,NONE
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,0,Nov,Monday,12-15,NONE
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,0,Nov,Tuesday,12-15,NONE
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,0,Aug,Tuesday,8-11,NONE
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,0,Oct,Sunday,16-19,NONE
150492,ASSAULT,2016-10-09 21:15:00,MISSION,0,Oct,Sunday,20-23,NONE
150493,ASSAULT,2016-10-21 13:30:00,MISSION,0,Oct,Friday,12-15,NONE
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,0,Dec,Thursday,20-23,NONE
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,0,Dec,Friday,8-11,NONE
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,0,Dec,Friday,12-15,NONE

In [124]:
a_bb={0:1 ,1:0}
df9.resolution=[a_bb[items] for items in df9.resolution]

In [125]:
df9

,category,crime_date,department_district,resolution,month,day_of_week,hour,res_arrest
2,WARRANTS,2016-04-25 14:59:00,BAYVIEW,0,April,Monday,12-15,"ARREST, BOOKED"
4,NON-CRIMINAL,2016-01-01 00:30:00,MISSION,1,Jan,Friday,0-3,NONE
5,ASSAULT,2016-01-01 21:35:00,NORTHERN,1,Jan,Friday,20-23,NONE
6,OTHER OFFENSES,2016-01-02 00:04:00,SOUTHERN,0,Jan,Saturday,0-3,"ARREST, BOOKED"
8,WARRANTS,2016-01-02 12:21:00,SOUTHERN,0,Jan,Saturday,12-15,"ARREST, BOOKED"
10,LARCENY/THEFT,2016-01-29 22:30:00,TARAVAL,1,Jan,Friday,20-23,NONE
11,NON-CRIMINAL,2016-01-02 13:30:00,TARAVAL,1,Jan,Saturday,12-15,NONE
12,OTHER OFFENSES,2016-01-25 23:20:00,BAYVIEW,0,Jan,Monday,20-23,"ARREST, BOOKED"
17,ASSAULT,2016-01-02 16:40:00,MISSION,1,Jan,Saturday,16-19,NONE
18,ASSAULT,2016-01-02 17:05:00,INGLESIDE,1,Jan,Saturday,16-19,NONE
25,OTHER OFFENSES,2016-01-03 15:09:00,TARAVAL,0,Jan,Sunday,12-15,"ARREST, BOOKED"
26,OTHER OFFENSES,2016-01-03 10:30:00,MISSION,1,Jan,Sunday,8-11,NONE
27,BURGLARY,2016-01-03 15:45:00,NORTHERN,0,Jan,Sunday,12-15,"ARREST, BOOKED"
28,OTHER OFFENSES,2016-01-03 17:02:00,MISSION,0,Jan,Sunday,16-19,"ARREST, BOOKED"
29,NON-CRIMINAL,2016-01-03 17:01:00,INGLESIDE,1,Jan,Sunday,16-19,NONE
30,VEHICLE THEFT,2016-01-03 15:40:00,CENTRAL,1,Jan,Sunday,12-15,NONE
32,LARCENY/THEFT,2016-02-16 12:40:00,INGLESIDE,1,Feb,Tuesday,12-15,NONE
35,OTHER OFFENSES,2016-02-16 16:35:00,MISSION,0,Feb,Tuesday,16-19,"ARREST, BOOKED"
36,NON-CRIMINAL,2016-01-03 19:45:00,INGLESIDE,1,Jan,Sunday,16-19,NONE
37,NON-CRIMINAL,2016-02-19 16:39:00,SOUTHERN,1,Feb,Friday,16-19,NONE
39,OTHER OFFENSES,2016-01-04 20:15:00,INGLESIDE,1,Jan,Monday,20-23,NONE
41,ASSAULT,2016-01-03 21:30:00,SOUTHERN,1,Jan,Sunday,20-23,NONE
42,LARCENY/THEFT,2016-01-04 19:40:00,MISSION,1,Jan,Monday,16-19,NONE
43,NON-CRIMINAL,2016-01-04 21:45:00,SOUTHERN,1,Jan,Monday,20-23,NONE
44,BURGLARY,2016-01-04 20:08:00,MISSION,1,Jan,Monday,20-23,NONE
46,BURGLARY,2016-10-26 19:37:00,INGLESIDE,0,Oct,Wednesday,16-19,"ARREST, BOOKED"
50,ASSAULT,2016-01-04 23:00:00,SOUTHERN,1,Jan,Monday,20-23,NONE
58,ASSAULT,2016-01-05 14:06:00,CENTRAL,1,Jan,Tuesday,12-15,NONE
59,OTHER OFFENSES,2016-01-05 15:15:00,NORTHERN,0,Jan,Tuesday,12-15,"ARREST, BOOKED"
60,OTHER OFFENSES,2016-01-05 15:14:00,BAYVIEW,0,Jan,Tuesday,12-15,"ARREST, BOOKED"
...,...,...,...,...,...,...,...,...
150448,ASSAULT,2016-04-29 10:00:00,SOUTHERN,1,April,Friday,8-11,NONE
150450,ASSAULT,2016-11-28 18:53:00,NORTHERN,1,Nov,Monday,16-19,NONE
150451,SUSPICIOUS OCC,2016-11-28 18:53:00,NORTHERN,1,Nov,Monday,16-19,NONE
150453,NON-CRIMINAL,2016-12-02 16:47:00,NORTHERN,1,Dec,Friday,16-19,NONE
150454,BURGLARY,2016-11-24 00:30:00,INGLESIDE,1,Nov,Thursday,0-3,NONE
150456,NON-CRIMINAL,2016-12-09 19:30:00,TARAVAL,1,Dec,Friday,16-19,NONE
150457,ASSAULT,2016-12-14 11:05:00,SOUTHERN,1,Dec,Wednesday,8-11,NONE
150461,LARCENY/THEFT,2016-12-28 22:34:00,CENTRAL,1,Dec,Wednesday,20-23,NONE
150463,NON-CRIMINAL,2016-03-04 15:00:00,NORTHERN,1,Mar,Friday,12-15,NONE
150465,ASSAULT,2016-06-16 16:30:00,BAYVIEW,1,June,Thursday,16-19,NONE
150467,LARCENY/THEFT,2016-04-05 20:00:00,CENTRAL,1,April,Tuesday,20-23,NONE
150468,NON-CRIMINAL,2016-04-05 23:15:00,CENTRAL,1,April,Tuesday,20-23,NONE
150469,LARCENY/THEFT,2016-04-15 23:01:00,MISSION,1,April,Friday,20-23,NONE
150473,NON-CRIMINAL,2016-05-07 00:40:00,CENTRAL,1,May,Saturday,0-3,NONE
150475,NON-CRIMINAL,2016-07-04 22:20:00,CENTRAL,1,July,Monday,20-23,NONE
150476,NON-CRIMINAL,2016-07-05 11:30:00,SOUTHERN,1,July,Tuesday,8-11,NONE
150477,LARCENY/THEFT,2016-05-16 13:09:00,CENTRAL,1,May,Monday,12-15,NONE
150478,NON-CRIMINAL,2016-07-10 16:00:00,SOUTHERN,1,July,Sunday,16-19,NONE
150480,NON-CRIMINAL,2016-08-15 21:45:00,CENTRAL,1,Aug,Monday,20-23,NONE
150481,NON-CRIMINAL,2016-09-05 10:30:00,TARAVAL,1,Sep,Monday,8-11,NONE
150484,NON-CRIMINAL,2016-11-29 17:00:00,SOUTHERN,1,Nov,Tuesday,16-19,NONE
150485,NON-CRIMINAL,2016-11-28 13:10:00,SOUTHERN,1,Nov,Monday,12-15,NONE
150486,LARCENY/THEFT,2016-11-22 13:58:00,CENTRAL,1,Nov,Tuesday,12-15,NONE
150490,ASSAULT,2016-08-16 10:00:00,BAYVIEW,1,Aug,Tuesday,8-11,NONE
150491,ASSAULT,2016-10-02 18:25:00,SOUTHERN,1,Oct,Sunday,16-19,NONE
150492,ASSAULT,2016-10-09 21:15:00,MISSION,1,Oct,Sunday,20-23,NONE
150493,ASSAULT,2016-10-21 13:30:00,MISSION,1,Oct,Friday,12-15,NONE
150497,LARCENY/THEFT,2016-12-29 20:00:00,CENTRAL,1,Dec,Thursday,20-23,NONE
150498,LARCENY/THEFT,2016-12-30 10:00:00,CENTRAL,1,Dec,Friday,8-11,NONE
150499,OTHER OFFENSES,2016-12-02 14:00:00,SOUTHERN,1,Dec,Friday,12-15,NONE

In [130]:
no_arst=df9['resolution']

In [131]:
no_arst

2         0
4         1
5         1
6         0
8         0
10        1
11        1
12        0
17        1
18        1
25        0
26        1
27        0
28        0
29        1
30        1
32        1
35        0
36        1
37        1
39        1
41        1
42        1
43        1
44        1
46        0
50        1
58        1
59        0
60        0
         ..
150448    1
150450    1
150451    1
150453    1
150454    1
150456    1
150457    1
150461    1
150463    1
150465    1
150467    1
150468    1
150469    1
150473    1
150475    1
150476    1
150477    1
150478    1
150480    1
150481    1
150484    1
150485    1
150486    1
150490    1
150491    1
150492    1
150493    1
150497    1
150498    1
150499    1
Name: resolution, Length: 79315, dtype: int64

# Merging Binary

In [135]:
df_j_1 = pd.merge(ctg, dfw, right_index=True, left_index=True)

In [137]:
df_j_3 = pd.merge(df_j_1, dd, right_index=True, left_index=True)

In [139]:
df_j_nrst=pd.merge(df_j_3, no_arst, right_index=True, left_index=True)

In [140]:
df_j_n_rst = pd.merge(df_j_nrst, hrr, right_index=True, left_index=True)

In [141]:
df_j_n_rst_wo_mnth = df_j_n_rst

In [ ]:
df_j_n_rst_wo_mnth_smtime = df_j_n_rst_wo_mnth.drop(['16-19'

],axis=1)

In [143]:
df_j_n_rst_wo_mnth.head()

,ASSAULT,BURGLARY,LARCENY/THEFT,NON-CRIMINAL,OTHER OFFENSES,SUSPICIOUS OCC,VANDALISM,VEHICLE THEFT,WARRANTS,Friday,...,MISSION,NORTHERN,SOUTHERN,TARAVAL,resolution,0-3,12-15,16-19,20-23,8-11
2,1,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,1,0,1,0,0,0
5,0,0,1,0,0,0,0,0,0,1,...,0,0,0,1,1,0,0,0,1,0
6,0,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
8,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [55]:
pip install kmodes

Requirement already satisfied: kmodes in c:\users\nikhil\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.10.4 in c:\users\nikhil\anaconda3\lib\site-packages (from kmodes) (1.16.2)
Requirement already satisfied: scipy>=0.13.3 in c:\users\nikhil\anaconda3\lib\site-packages (from kmodes) (1.2.1)
Requirement already satisfied: joblib>=0.11 in c:\users\nikhil\anaconda3\lib\site-packages (from kmodes) (0.14.1)
Requirement already satisfied: scikit-learn>=0.19.0 in c:\users\nikhil\anaconda3\lib\site-packages (from kmodes) (0.20.3)
Note: you may need to restart the kernel to use updated packages.

In [56]:
from kmodes.kmodes import KModes

# Model having variable
## 1. Hour
## 2. Not arrested
## 3. Day of week(Sunday, Monady,Tuesday etc.)
## 4. Category
## 5. Department district(Area like Mission, Central, Bayview etc).

In [66]:
print("without month\n\n\n")

# define the k-modes model
km = KModes(n_clusters=10, init='Huang', n_init=20, verbose=1)
# fit the clusters to the skills dataframe
clusters = km.fit_predict(df_j_n_rst_wo_mnth)
# get an array of cluster modes
kmodes = km.cluster_centroids_
shape = kmodes.shape
# For each cluster mode (a vector of "1" and "0")
# find and print the column headings where "1" appears.
# If no "1" appears, assign to "no-skills" cluster.
for i in range(shape[0]):
    if sum(kmodes[i,:]) == 0:
        print("\ncluster " + str(i) + ": ")
        print("no-skills cluster")
    else:
        print("\ncluster " + str(i) + ": ")
        cent = kmodes[i,:]
        for j in df_j_n_rst_wo_mnth.columns[np.nonzero(cent)]:
            print(j)
            
            
            
            
            
#   res_arrest means no arest in output           
            
print("without month, res_arrest means no arest in output \n\n\n")

# define the k-modes model
km = KModes(n_clusters=10, init='Huang', n_init=20, verbose=1)
# fit the clusters to the skills dataframe
clusters = km.fit_predict(df_j_n_rst_wo_mnth_smtime)
# get an array of cluster modes
kmodes = km.cluster_centroids_
shape = kmodes.shape
# For each cluster mode (a vector of "1" and "0")
# find and print the column headings where "1" appears.
# If no "1" appears, assign to "no-skills" cluster.
for i in range(shape[0]):
    if sum(kmodes[i,:]) == 0:
        print("\ncluster " + str(i) + ": ")
        print("no-skills cluster")
    else:
        print("\ncluster " + str(i) + ": ")
        cent = kmodes[i,:]
        for j in df_j_n_rst_wo_mnth_smtime.columns[np.nonzero(cent)]:
            print(j)
            
            
            
# res_arrest means no arest in output

without month



Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 16068, cost: 126780.0
Run 1, iteration: 2/100, moves: 2363, cost: 126780.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 18435, cost: 129089.0
Run 2, iteration: 2/100, moves: 69, cost: 129089.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 18465, cost: 122540.0
Run 3, iteration: 2/100, moves: 634, cost: 122540.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 17888, cost: 123176.0
Run 4, iteration: 2/100, moves: 5046, cost: 123176.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 18863, cost: 125181.0
Run 5, iteration: 2/100, moves: 1942, cost: 125181.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/100, moves: 15386, cost: 124438.0
Run 6, iteration: 2/100, moves: 1657, cost: 124438.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 7, iteration: 1/100, moves: 19619, cost: 122338.0
Run 7, iteration: 2/100, moves: 1737, cost: 122338.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 8, iteration: 1/100, moves: 18732, cost: 124220.0
Run 8, iteration: 2/100, moves: 4669, cost: 123520.0
Run 8, iteration: 3/100, moves: 506, cost: 123520.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 9, iteration: 1/100, moves: 17968, cost: 127550.0
Run 9, iteration: 2/100, moves: 2482, cost: 125007.0
Run 9, iteration: 3/100, moves: 2385, cost: 125007.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 10, iteration: 1/100, moves: 14930, cost: 129499.0
Run 10, iteration: 2/100, moves: 2139, cost: 129499.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 11, iteration: 1/100, moves: 15338, cost: 126288.0
Run 11, iteration: 2/100, moves: 3543, cost: 126035.0
Run 11, iteration: 3/100, moves: 67, cost: 126035.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 12, iteration: 1/100, moves: 17378, cost: 123761.0
Run 12, iteration: 2/100, moves: 1699, cost: 123761.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 13, iteration: 1/100, moves: 17892, cost: 117564.0
Run 13, iteration: 2/100, moves: 2389, cost: 117564.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 14, iteration: 1/100, moves: 20228, cost: 124373.0
Run 14, iteration: 2/100, moves: 1000, cost: 124373.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 15, iteration: 1/100, moves: 18746, cost: 135517.0
Run 15, iteration: 2/100, moves: 1666, cost: 135517.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 16, iteration: 1/100, moves: 14896, cost: 131221.0
Run 16, iteration: 2/100, moves: 4265, cost: 130129.0
Run 16, iteration: 3/100, moves: 276, cost: 130129.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 17, iteration: 1/100, moves: 18159, cost: 125755.0
Run 17, iteration: 2/100, moves: 3959, cost: 125206.0
Run 17, iteration: 3/100, moves: 1390, cost: 124791.0
Run 17, iteration: 4/100, moves: 2418, cost: 121634.0
Run 17, iteration: 5/100, moves: 1902, cost: 121634.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 18, iteration: 1/100, moves: 17924, cost: 125533.0
Run 18, iteration: 2/100, moves: 2081, cost: 124467.0
Run 18, iteration: 3/100, moves: 3218, cost: 122732.0
Run 18, iteration: 4/100, moves: 634, cost: 122732.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 19, iteration: 1/100, moves: 19408, cost: 127909.0
Run 19, iteration: 2/100, moves: 1351, cost: 127909.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 20, iteration: 1/100, moves: 17812, cost: 121965.0
Run 20, iteration: 2/100, moves: 2098, cost: 121965.0
Best run was number 13

cluster 0:
res_arrest
16-19

cluster 1:
res_arrest
8-11

cluster 2:
SOUTHERN
res_arrest
16-19

cluster 3:
res_arrest
12-15

cluster 4:
LARCENY/THEFT
Sunday
CENTRAL
res_arrest
12-15

cluster 5:
LARCENY/THEFT
SOUTHERN
12-15

cluster 6:
res_arrest
20-23

cluster 7:
20-23

cluster 8:
LARCENY/THEFT
NORTHERN
16-19

cluster 9:
Thursday
res_arrest
12-15
without month



Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 17800, cost: 122792.0
Run 1, iteration: 2/100, moves: 2754, cost: 121316.0
Run 1, iteration: 3/100, moves: 455, cost: 121316.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 12186, cost: 116203.0
Run 2, iteration: 2/100, moves: 0, cost: 116203.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 16206, cost: 123040.0
Run 3, iteration: 2/100, moves: 2278, cost: 123040.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 16575, cost: 120154.0
Run 4, iteration: 2/100, moves: 3737, cost: 119181.0
Run 4, iteration: 3/100, moves: 205, cost: 119181.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 16496, cost: 121731.0
Run 5, iteration: 2/100, moves: 904, cost: 121731.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/100, moves: 13809, cost: 121200.0
Run 6, iteration: 2/100, moves: 0, cost: 121200.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 7, iteration: 1/100, moves: 21018, cost: 115883.0
Run 7, iteration: 2/100, moves: 1879, cost: 115883.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 8, iteration: 1/100, moves: 13339, cost: 119773.0
Run 8, iteration: 2/100, moves: 1813, cost: 119773.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 9, iteration: 1/100, moves: 18675, cost: 119847.0
Run 9, iteration: 2/100, moves: 4098, cost: 118210.0
Run 9, iteration: 3/100, moves: 1148, cost: 118210.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 10, iteration: 1/100, moves: 19423, cost: 119053.0
Run 10, iteration: 2/100, moves: 5035, cost: 118185.0
Run 10, iteration: 3/100, moves: 1293, cost: 118185.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 11, iteration: 1/100, moves: 18136, cost: 118316.0
Run 11, iteration: 2/100, moves: 4590, cost: 117758.0
Run 11, iteration: 3/100, moves: 715, cost: 117758.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 12, iteration: 1/100, moves: 12675, cost: 124993.0
Run 12, iteration: 2/100, moves: 768, cost: 124993.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 13, iteration: 1/100, moves: 15653, cost: 120762.0
Run 13, iteration: 2/100, moves: 3330, cost: 120762.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 14, iteration: 1/100, moves: 21206, cost: 120772.0
Run 14, iteration: 2/100, moves: 1217, cost: 120772.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 15, iteration: 1/100, moves: 15942, cost: 115599.0
Run 15, iteration: 2/100, moves: 1760, cost: 115599.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 16, iteration: 1/100, moves: 17876, cost: 119653.0
Run 16, iteration: 2/100, moves: 1947, cost: 119653.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 17, iteration: 1/100, moves: 19450, cost: 120122.0
Run 17, iteration: 2/100, moves: 2098, cost: 120122.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 18, iteration: 1/100, moves: 15164, cost: 122245.0

Run 18, iteration: 2/100, moves: 0, cost: 122245.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 19, iteration: 1/100, moves: 14393, cost: 122212.0
Run 19, iteration: 2/100, moves: 0, cost: 122212.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 20, iteration: 1/100, moves: 19841, cost: 119402.0
Run 20, iteration: 2/100, moves: 614, cost: 119402.0
Best run was number 15

cluster 0:
OTHER OFFENSES
res_arrest
12-15

cluster 1:
VANDALISM
res_arrest

cluster 2:
MISSION

cluster 3:
LARCENY/THEFT
CENTRAL
res_arrest

cluster 4:
20-23

cluster 5:
Saturday
res_arrest

cluster 6:
LARCENY/THEFT
SOUTHERN
res_arrest

cluster 7:
NON-CRIMINAL
Friday
res_arrest

cluster 8:
LARCENY/THEFT
NORTHERN
res_arrest

cluster 9:
Wednesday
res_arrest

# Findings


## 1. from cluster cluster 4: CENTRAL, Sunday, LARCENY/THEFT,  res_arrest, 12-15.
###    In region CENTRAL on SUNDAY their is a high chance of  LARCENY/THEFT between Time 12-15 in which their is No Arrest was happened.

##  


## 2. from cluster cluster 5: SOUTHERN, res_arrest, 16-19.   
###    In region SOUTHERN between Time 16-19 in which their is No Arrest was happened for the criminal offences.

###   

## 3. from cluster cluster 8: LARCENY/THEFT, NORTHERN, 16-19. 
###    In region NORTHERN between Time 16-19  there is high chances of LARCENY/THEFT.


##  


## 4. from cluster cluster 9: Thursday, res_arrest, 12-15.
###   On Thursday between time 12-15 the crime offences have No Arrest factor was large.
###  

## 5. from other clusters no concrete conclusion can be derived.

##   
# Summary:- 
# 1. Time between 12-15(i.e12.00-15.59) is critical time from crime perspective.
##          a) On Thursday as their is high chance of No Arrest(Criminal escape).
##          b) On Sunday at Central Region for Larceny/Theft crime, Criminal did not Abducted/Areested.

##    
# 2. Time between 16-19(i.e16.00-19.59) is critical time from crime perspective. 
##           a) Crime happened on southern region has less Arrest factor.
##           b) Larceny/Theft crime factor was large in  Northen region.